### ISSUE TITLE
stripColorCode doesn't account for other valid formats

### ISSUE THREAD

**Issue by cbortz** [Sobuno/SWGAide#4] opened 2016-04-15 07:56 UTC
The [regex used to strip color codes](https://github.com/Sobuno/SWGAide/blob/b98d1de7f9f43572530154d175feae0c794c7d84/swg/gui/common/SWGGuiUtils.java#L521) does not include complete coverage for color codes with a trailing slash (also [valid syntax](http://www.swgemu.com/archive/scrapbookv51/data/20070210171909/)) (ex. `\#ff0000\`).

I believe what you would want is a pattern that allows for an options trailing slash. Thoughts?

**Comment by Sobuno** [comment] 2016-04-15 17:36
The issue is fixed by your pull request (Merged as c5b67acc), thanks! Closing this issue.

**Closed as completed by Sobuno** 2016-04-15 17:36 UTC
